spring:
  application:
    name: expert

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/expert
    password: Plqafgh12!

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        show_sql: true

jwt:
  secret:
    key: DBWrjBFv78AzkggUVxKiPngUEfvR0uECpz4qJut+jLM=