spring:
  application:
    name: expert

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        show_sql: true

server:
  port: ${PORT:8080}

jwt:
  secret:
    key: ${jwt.secret.key}